# TP1: Iris Dataset

# A- Importation des librairies

In [56]:
from sklearn import *
import numpy as np

In [ ]:
B- Manipulation d'un jeu de données

In [57]:
iris = datasets.load_iris()

In [58]:
print(iris.data)
print(iris.feature_names)
print(iris.target_names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

3-Display each data with his class

In [59]:
for data, name in zip(iris.data, iris.target):
    print(data, " ", iris.target_names[name])

[5.1 3.5 1.4 0.2]   setosa
[4.9 3.  1.4 0.2]   setosa
[4.7 3.2 1.3 0.2]   setosa
[4.6 3.1 1.5 0.2]   setosa
[5.  3.6 1.4 0.2]   setosa
[5.4 3.9 1.7 0.4]   setosa
[4.6 3.4 1.4 0.3]   setosa
[5.  3.4 1.5 0.2]   setosa
[4.4 2.9 1.4 0.2]   setosa
[4.9 3.1 1.5 0.1]   setosa
[5.4 3.7 1.5 0.2]   setosa
[4.8 3.4 1.6 0.2]   setosa
[4.8 3.  1.4 0.1]   setosa
[4.3 3.  1.1 0.1]   setosa
[5.8 4.  1.2 0.2]   setosa
[5.7 4.4 1.5 0.4]   setosa
[5.4 3.9 1.3 0.4]   setosa
[5.1 3.5 1.4 0.3]   setosa
[5.7 3.8 1.7 0.3]   setosa
[5.1 3.8 1.5 0.3]   setosa
[5.4 3.4 1.7 0.2]   setosa
[5.1 3.7 1.5 0.4]   setosa
[4.6 3.6 1.  0.2]   setosa
[5.1 3.3 1.7 0.5]   setosa
[4.8 3.4 1.9 0.2]   setosa
[5.  3.  1.6 0.2]   setosa
[5.  3.4 1.6 0.4]   setosa
[5.2 3.5 1.5 0.2]   setosa
[5.2 3.4 1.4 0.2]   setosa
[4.7 3.2 1.6 0.2]   setosa
[4.8 3.1 1.6 0.2]   setosa
[5.4 3.4 1.5 0.4]   setosa
[5.2 4.1 1.5 0.1]   setosa
[5.5 4.2 1.4 0.2]   setosa
[4.9 3.1 1.5 0.2]   setosa
[5.  3.2 1.2 0.2]   setosa
[5.5 3.5 1.3 0.2]   setosa
[

4.1-Mean according to column

In [60]:
iris.data.mean(0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

4.2-Ecart-type according to column

In [61]:
np.std(iris.data, axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

4.3-Min according to column

In [62]:
np.min(iris.data, axis=0)

array([4.3, 2. , 1. , 0.1])

4.4-Max according to column

In [63]:
np.max(iris.data, axis=0)

array([7.9, 4.4, 6.9, 2.5])

5-