## A. Normalisation

In [5]:
import numpy as np
# 1. Creation de matrice X
X = np.array([[1, -1, 2],[2, 0, 0], [0, 1, -1]])
print(X)
# Moyenne et Variance de X
print("The mean: ",X.mean())
print("The variance: ", X.var())

[[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]
The mean:  0.4444444444444444
The variance:  1.1358024691358024


In [15]:
#normalized = X/X.sum(axis=1)[:, np.newaxis]
norm = X/np.linalg.norm(X, axis=1)
print(np.linalg.norm(X, axis=1))
norm

[2.44948974 2.         1.41421356]


array([[ 0.40824829, -0.5       ,  1.41421356],
       [ 0.81649658,  0.        ,  0.        ],
       [ 0.        ,  0.5       , -0.70710678]])

In [19]:
norm = 0;
for i in range(3):
    norm = 0;
    for j in range(3):
        norm += pow(X[i][j],2)
    norm = sqrt(norm);
    for j in range(3):
        X[i][j]= X[i][j] / norm 
X

NameError: name 'sqrt' is not defined